[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
puppet = "7YWUjFm6NtfzSJjTfRBuR65V3N5Zoi2wDDasdxkkJZcF"
puppet_master = "958SimwcmR2YVwJGUsmLD1t73hnwVms1A4ScCRg9ExSQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/shada/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 60  # Increase the value to 60 seconds or more
